version: '2.2'
services:
  fpausercentre:
    build:
      context: .
      dockerfile: Dockerfile
    image: fpausercentre
    ports:
      - 8080
    networks:
      - front-tier
      - back-tier
    scale: 3
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - fpausercentre
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
